# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2
builds:
  - skip: true
archives:
  - formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}"
changelog:
  disable: false
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Doc updates"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other updates"
      order: 999
