#!/usr/bin/env sh

usage () {
  echo "Usage: avm <make target>"
}

CONTAINER_RUNTIME=${CONTAINER_RUNTIME:-docker}

if [ ! "$(command -v "$CONTAINER_RUNTIME")" ]; then
    echo "Error: $CONTAINER_RUNTIME is not installed. Please install $CONTAINER_RUNTIME first."
    exit 1
fi

if [ -z "$1" ]; then
    echo "Error: Please provide a make target. See https://github.com/Azure/avm-terraform-governance/blob/main/Makefile for available targets."
    echo
    usage
    exit 1
fi

# Check if AZURE_CONFIG_DIR is set, if not, set it to ~/.azure
if [ -z "$AZURE_CONFIG_DIR" ]; then
  AZURE_CONFIG_DIR="$HOME/.azure"
fi

# If we are not in GitHub Actions, we want to use TUI and interactive mode
if [ -z "$GITHUB_RUN_ID" ]; then
  TUI="--tui"
  DOCKER_INTERACTIVE="-it"
  export FORCE_COLOR=1
fi

# Check if we are running in a container
# If we are then just run make directly
if [ -z "$AVM_IN_CONTAINER" ]; then
  $CONTAINER_RUNTIME run \
    --pull always \
    --user "$(id -u):$(id -g)" \
    --rm \
    $DOCKER_INTERACTIVE \
    -v "$(pwd)":/src \
    -v $AZURE_CONFIG_DIR:/azureconfig \
    -e ARM_CLIENT_ID \
    -e ARM_SUBSCRIPTION_ID \
    -e ARM_TENANT_ID \
    -e AZURE_CONFIG_DIR=/azureconfig \
    -e FORCE_COLOR \
    -e GITHUB_TOKEN \
    -e NO_COLOR \
    -e PORCH_LOG_LEVEL \
    -e TEST_TYPE \
    ghcr.io/azure/avm-terraform-governance:latest \
    make \
    TUI="$TUI" \
    "$1"
else
  make TUI="$TUI" "$1"
fi
